.TH "library/src/boole.c" 3 "Lun 16 Mag 2011" "Version stringpool" "StringPool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
library/src/boole.c \- 
.PP
Implementazione boole.  

.SH SYNOPSIS
.br
.PP
.SH "Descrizione dettagliata"
.PP 
Implementazione boole. 

Contiene funzioni ed implementazioni di booleani 
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per StringPool a partire dal codice sorgente.
