.TH "Library/bool.h" 3 "Lun 30 Mag 2011" "Version 1.0" "Stringpool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Library/bool.h \- 
.PP
Header per valori Booleani.  

.SH SYNOPSIS
.br
.PP
.SS "Definizioni"

.in +1c
.ti -1c
.RI "#define \fBBOOLE_H_\fP"
.br
.in -1c
.SS "Tipi enumerati (enum)"

.in +1c
.ti -1c
.RI "enum \fBboolean\fP { \fBFALSE\fP =  0, \fBTRUE\fP =  1 }"
.br
.RI "\fITipo di dato non primitivo boolean. \fP"
.in -1c
.SH "Descrizione dettagliata"
.PP 
Header per valori Booleani. 

\fBAutore:\fP
.RS 4
Domenico Monaco, domenico.monaco@kiuz.it 
.RE
.PP
\fBData:\fP
.RS 4
2011 
.RE
.PP
.SH "Licenza"
.PP
GPLv2 http://www.softwarelibero.it/gnudoc/gpl.it.txt Per maggiori informazioni visitare il link o visualizzare il file LICENSE 
.SH "Documentazione delle definizioni"
.PP 
.SS "#define BOOLE_H_"Impedisce inclusioni multiple 
.SH "Documentazione dei tipi enumerati"
.PP 
.SS "enum Definizione del tipo \fBboolean\fP"
.PP
Tipo di dato non primitivo boolean. vale 1 se TRUE, 0 se FALSE 
.PP
\fBValori del tipo enumerato: \fP
.in +1c
.TP
\fB\fIFALSE \fP\fP
valore boolean FALSE = 0 
.TP
\fB\fITRUE \fP\fP
valore boolean TRUE = 1 
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per Stringpool a partire dal codice sorgente.
