.TH "library/src/boole.h" 3 "Lun 16 Mag 2011" "Version stringpool" "StringPool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
library/src/boole.h \- 
.PP
Header boole.  

.SH SYNOPSIS
.br
.PP
.SH "Descrizione dettagliata"
.PP 
Header boole. 

Contiene prototipi e strutture per booleani 
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per StringPool a partire dal codice sorgente.
