.TH "_Other_test/main/src/main.c" 3 "Lun 16 Mag 2011" "Version stringpool" "StringPool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Other_test/main/src/main.c \- 
.PP
File principale.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
File principale. 

Contiene funzione main e interfaccia con le librerie.
.SH "Copyright"
.PP
Domenico Monaco 2011 
.SH "License"
.PP
GPLv2 - Testo originale: http://www.gnu.org/licenses/gpl-2.0.html
.PP
Traduzione in lingua italiana: http://www.softwarelibero.it/gnudoc/gpl.it.txt
.PP
\fBAutore:\fP
.RS 4
Domenico Monaco 
.RE
.PP
\fBVersione:\fP
.RS 4
0.1 
.RE
.PP
\fBData:\fP
.RS 4
2011
.RE
.PP
\fBBug\fP
.RS 4
lista di descrizioni di bug 
.PP
... 
.RE
.PP
\fBAvvertimento:\fP
.RS 4
lista di descrizioni di warning 
.PP
... 
.RE
.PP

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per StringPool a partire dal codice sorgente.
