.TH ".metadata/.plugins/org.eclipse.cdt.make.core/specs.c" 3 "Ven 27 Mag 2011" "Version 1.0" "StringPool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
.metadata/.plugins/org.eclipse.cdt.make.core/specs.c \- 
.SH SYNOPSIS
.br
.PP
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per StringPool a partire dal codice sorgente.
