.TH "library/src/spstring.h" 3 "Lun 16 Mag 2011" "Version stringpool" "StringPool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
library/src/spstring.h \- 
.PP
Header spstring.  

.SH SYNOPSIS
.br
.PP
.SS "Variabili"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBstring\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Header spstring. 

Contiene i prototipi e le strutture della libreria 'spstring' 
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per StringPool a partire dal codice sorgente.
