.TH "library/src/spstring.c" 3 "Lun 16 Mag 2011" "Version stringpool" "StringPool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
library/src/spstring.c \- 
.PP
Implementazione spstring.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Implementazione spstring. 

Contiene il codice di implementazione delle funzioni della libreria 'spstring' La libreria stringpool offre i servizi seguenti attraverso funzioni di libreria rivolti alla manipolazione di stringpool, cioè di un insieme di stringhe. Inoltre, la libreria permette di ordinare un array di stringhe in ordine alfabetico, salvare e caricare un array da file di test, ed effettuare la ricerca binaria di un elemento 
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per StringPool a partire dal codice sorgente.
