.TH "stringpool_lib/src/stringpool_lib.h" 3 "Lun 16 Mag 2011" "Version stringpool" "StringPool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stringpool_lib/src/stringpool_lib.h \- 
.PP
Stringpool header file.  

.SH SYNOPSIS
.br
.PP
.SH "Descrizione dettagliata"
.PP 
Stringpool header file. 


.SH "Autore"
.PP 
Generato automaticamente da Doxygen per StringPool a partire dal codice sorgente.
